name: Build and Deploy

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --no-restore --configuration Release

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal

      - name: Build Docker Image
        run: docker build -t myapp:latest .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: MyAzureApp
          slot-name: production
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}

      - name: Slack Notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "channel": "#ci-cd",
              "text": "Build and Tests passed successfully for commit: ${{ github.sha }}"
            }
          token: ${{ secrets.SLACK_BOT_TOKEN }}
