name: CI - Test and Lint

on:
  push:
    branches:
      - m

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Check Code Formatting
        run: dotnet format --check

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal
